# Python for Economics and Finance
## Scientific Library: 1 Introduction to Numpy
### Shutao Cao
#### 2026-01-23

## Outline
- [Overview](#Overview)
- [Creating arrays](#Creating-arrays)
- [Array index and slicing](#Array-index-and-slicing)
- [Array manipulation](#Array-manipulation)
- [Copies and Views](#Copies-and-Views)
- [Computation on arrays](#Computation-on-arrays)
- [File Input and Output](#File-Input-and-Output)

## Overview
[NumPy](https://numpy.org/) is the fundamental package for scientific computing in Python. 

It provides multidimensional array objects, various derived objects (such as masked arrays and matrices), and may routines of fast array operations.

These operations include
- mathematical and logical operations
- shape manipulation
- sorting
- discrete Fourier transforms
- basic linear algebra
- basic statistical operations
- random number generation.

### Differences between Numpy arrays and Python lists
- NumPy arrays have a fixed size at creation, while the length of a Python list can change dynamically.
- Elements in a NumPy array much have the same data type, while data types of elements in a Python list can be mixed.
- NumPy arrays allow mathematical and other operations on large numbers of data. Mathematical operations on list is very limited.
- Pretty much all scientific and mathematical Python-based packages use NumPy arrays, not Python lists.

## Creating arrays
At the core of Numpy is the _ndarray_ object, the n-dimensional arrays of homogeneous data types.

Selected methods of creating arrays:

| Function Name    |         Type of Array   |
| :----------------|  :--------------------  |
| np.array | Creates an array from a list or a tuple |
| np.arange   |  Creates an array with evenly spaced values between a starting value and an end value |
| np.linspace   |  Creates an array with evenly spaced values between specified start and end values |
| np.logspace   |  Creates an array with values that are logarithmically spaced between given start and end values |
| np.meshgrid   |  Generates coordinate matrices (and high-dimensional coordinate arrays) from one-dimensional coordinate vectors |
| np.fromfunction   |  Creates an array that accords to certain functions |   
 np.zeros   |  Creates an array of zeros  |
| np.ones   |  Creates an array of ones |
| np.diag   |  Creates a diagonal array |

In addition, we can read data files into an array directly.

### Indexing elements of a two-dimensional array
![Two-dimensional Array](two_dim_Array.png)

In [83]:
import numpy as np        # convention to name numpy as np
x = np.array([0,1,2,3,4])
print('x =',x)
x = np.array((0,1,2,3,4), dtype=float)
print('x =',x)
y = np.array([[1,2,3],[4,5,6]])
print ('y=',y)

x = [0 1 2 3 4]
x = [0. 1. 2. 3. 4.]
y= [[1 2 3]
 [4 5 6]]


In [84]:
a = np.arange(2,12, 2)
a

array([ 2,  4,  6,  8, 10])

In [85]:
a = np.linspace(-np.pi, np.pi, 6)    # Create even grid from -π to π
print('a=', a)

a= [-3.14159265 -1.88495559 -0.62831853  0.62831853  1.88495559  3.14159265]


`numpy.fromfunction` constructs an array by executing a function over each coordinate.

The example below create a 2 by 3 array from lambda function, x takes values 0,1 and y take values 0,1,2.

First row, x=0, thus, x*3+y+1 takes three values: 0+1, 1+2, 2+1.

Second row, x=1, thus, x*3+y+1 takes values: 1*3+0+1, 1*3+1+1, 1*3+2+1.

In [86]:
a = np.fromfunction(lambda x, y: x*3 + y + 1, (2,3))
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [87]:
a = np.ones((3, 3,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [88]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [90]:
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [91]:
a = np.full((2, 3), 3.14)
a

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [92]:
a = np.meshgrid([1,2],[3,4,5])
a

(array([[1, 2],
        [1, 2],
        [1, 2]]),
 array([[3, 3],
        [4, 4],
        [5, 5]]))

### Array attributes

In [93]:
a = np.fromfunction(lambda x, y: x*3 + y + 1, (2,3))
print("a ndim: ", a.ndim)
print("a shape:", a.shape)
print("a size: ", a.size)
print("a dtype:", a.dtype)

a ndim:  2
a shape: (2, 3)
a size:  6
a dtype: float64


## Array index and slicing

This table shows the slicing of one-dimensional arrays. They apply to one dimension in an n-dimensional array.
|  Slicing   |  Description   |
|  :-------  |  :--------  |
|  a[m]   |  select the $(m+1)$-th element  |
|  a[-m]   |  select the $m$th element from the end of array |
|  a[m:n]   |  select elements from position $m+1$ to position $n−1$ |
|  a[:]  |  select all elements in the given axis, same as a[0:-1]  |
|  a[:n]   |  select elements before the $n$th element |
|  a[m:]  |  select elements that follow the $(m+1)$-th element, same as a[m:-1] |
|  a[m:n:p]   |  select elements from $(m+1)$-th through the $(n-1)$th (exclusive), with increment p |
|  a[::-1]   |  select all the elements, in reverse order   |


In [94]:
a = np.fromfunction(lambda x, y: x*3 + y + 1, (3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 4.,  5.,  6.,  7.],
       [ 7.,  8.,  9., 10.]])

In [95]:
a[1,2]

np.float64(6.0)

In [96]:
a[[1,1],[2,-1]]

array([6., 7.])

In [97]:
a[-2]

array([4., 5., 6., 7.])

In [98]:
a[-2,:]

array([4., 5., 6., 7.])

In [99]:
a[1,0:3]

array([4., 5., 6.])

In [100]:
a[:,-2]

array([3., 6., 9.])

In [101]:
a[::-1]

array([[ 7.,  8.,  9., 10.],
       [ 4.,  5.,  6.,  7.],
       [ 1.,  2.,  3.,  4.]])

In [102]:
a[::-1,::-1]

array([[10.,  9.,  8.,  7.],
       [ 7.,  6.,  5.,  4.],
       [ 4.,  3.,  2.,  1.]])

In [103]:
a[0,1] = -1.68
a

array([[ 1.  , -1.68,  3.  ,  4.  ],
       [ 4.  ,  5.  ,  6.  ,  7.  ],
       [ 7.  ,  8.  ,  9.  , 10.  ]])

In [104]:
a[2,:] = [10,20,30,40]
a

array([[ 1.  , -1.68,  3.  ,  4.  ],
       [ 4.  ,  5.  ,  6.  ,  7.  ],
       [10.  , 20.  , 30.  , 40.  ]])

In [105]:
# Boolean indexing
b = a[a>5]
b

array([ 6.,  7., 10., 20., 30., 40.])

In [106]:
# fancy indexing
a = np.linspace(1.0, 6.5,12)
print('a =',a)
# choose elements in positions: 3, 5,7,10
b = a[[3,5,7,10]]
print('b =',b)

a = [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]
b = [2.5 3.5 4.5 6. ]


## Array manipulation

See [https://numpy.org/doc/stable/reference/routines.array-manipulation.html](https://numpy.org/doc/stable/reference/routines.array-manipulation.html)

Selected methods of array manipulation:

| Function/Method    | Description                    |
| :---------------- | :------------------------------ |
| np.reshape or np.ndarray.reshape  | Reshapes an $n$-dimensional array. The number of elements remains the same |
| np.ndarray.flatten  | Returns a copy of the array collapsed into one dimension |
| np.ravel or  np.ndarray.ravel | Returns a contiguous flattened array |
| np.squeeze  | Removes axes with length 1.  |
| np.expand_dims  | Adds a new axis (dimension) of length 1 to an array, where np.newaxis is used with array indexing  |
| np.transpose or np.ndarray.T | Transposes the array |
| np.concatenate  | Creates a new array by appending arrays to each other, along a given axis  |
| np.hstack  | Stacks a list of arrays along axis 1 (row wise) |
| np.vstack  | Stacks a list of arrays along axis 0 (column wise) |
| np.dstack  | Stacks arrays depth-wise (along third axis)  |
| np.resize  | Creates a new array, with the requested size |
| np.append  | Appends an element to an array. Creates a new copy of the array.  |
| np.insert  | Inserts a new element at a given position. Creates a new copy of the array |
| np.delete  | Deletes an element at a given position. Creates a new copy of the array  |


### Reshaping
Reshaping an array take two types of order:
-  `order=‘C’` means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. In the two-dimension case, `reshape` reads first the first row (which is the index 1), then the second row, and so on.
-  `order=‘F’` means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. In the two-dimension case, `reshape` reads first the first column (which is the index 0), then the second column, and so on.

In [107]:
a = np.fromfunction(lambda x, y: x*4+y+3, (3,4))
print('a =',a)
b = a.reshape((2,6))
print('b =',b)

a = [[ 3.  4.  5.  6.]
 [ 7.  8.  9. 10.]
 [11. 12. 13. 14.]]
b = [[ 3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14.]]


In [108]:
b = np.reshape(a,(2,6))  # does the same thing as b = a.reshape((2,6))
print('b =',b)

b = [[ 3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14.]]


In [109]:
b = a.reshape((2,6),order='C')
b

array([[ 3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14.]])

In [110]:
b = a.reshape((2,6),order='F')
b

array([[ 3., 11.,  8.,  5., 13., 10.],
       [ 7.,  4., 12.,  9.,  6., 14.]])

In [111]:
b_c = a.reshape(12,order='C')
b_f = a.reshape(12,order='F')
print('b_c =', b_c)
print('b_f =', b_f)

b_c = [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
b_f = [ 3.  7. 11.  4.  8. 12.  5.  9. 13.  6. 10. 14.]


### Flattening

Methods ravel and flatten appear to do the same thing. But according to Numpy manual:
- `ravel` returns a view of reshaped original array.
- `flatten` returns a copy of reshaped original array.

In [112]:
a = np.fromfunction(lambda x, y: x*3+y*2+1, (3,4))
print('a =',a)

a = [[ 1.  3.  5.  7.]
 [ 4.  6.  8. 10.]
 [ 7.  9. 11. 13.]]


In [113]:
b = a.ravel()
b

array([ 1.,  3.,  5.,  7.,  4.,  6.,  8., 10.,  7.,  9., 11., 13.])

In [114]:
b = a.ravel(order='F')
b

array([ 1.,  4.,  7.,  3.,  6.,  9.,  5.,  8., 11.,  7., 10., 13.])

In [115]:
print(b.shape)
b[1,]=-4
print('a =',a)

(12,)
a = [[ 1.  3.  5.  7.]
 [ 4.  6.  8. 10.]
 [ 7.  9. 11. 13.]]


In [116]:
b = a.flatten()
print(b.shape)
b

(12,)


array([ 1.,  3.,  5.,  7.,  4.,  6.,  8., 10.,  7.,  9., 11., 13.])

In [117]:
b=a.flatten(order='F')
b

array([ 1.,  4.,  7.,  3.,  6.,  9.,  5.,  8., 11.,  7., 10., 13.])

### Transpose

In [118]:
b = a.T
b

array([[ 1.,  4.,  7.],
       [ 3.,  6.,  9.],
       [ 5.,  8., 11.],
       [ 7., 10., 13.]])

In [119]:
b = a.transpose()
b

array([[ 1.,  4.,  7.],
       [ 3.,  6.,  9.],
       [ 5.,  8., 11.],
       [ 7., 10., 13.]])

### Stacking and splitting

In [120]:
x = np.arange(0, 5, 0.5)
nx = x.size
y = np.linspace(2,20,nx)
b = np.vstack((x,x,y))
b

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5],
       [ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5],
       [ 2. ,  4. ,  6. ,  8. , 10. , 12. , 14. , 16. , 18. , 20. ]])

In [121]:
c = np.vsplit(b,3)
c

[array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]]),
 array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]]),
 array([[ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.]])]

In [122]:
b = np.hstack((x,y))
b

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  2. ,
        4. ,  6. ,  8. , 10. , 12. , 14. , 16. , 18. , 20. ])

In [123]:
c = np.hsplit(b,2)
c

[array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])]

### Resizing

In [124]:
a = np.fromfunction(lambda x, y: x*3+y*2+1, (3,4))
print('a =',a)
b = np.resize(a, (2,3))
print('b =',b)

a = [[ 1.  3.  5.  7.]
 [ 4.  6.  8. 10.]
 [ 7.  9. 11. 13.]]
b = [[1. 3. 5.]
 [7. 4. 6.]]


## Copies and Views
In operations and manipulations on an array, data in the array sometimes are copied to new arrays, but sometimes are not.

There are three cases.

Case 1: Simple assignments make no copy of objects or their data

In [125]:
x = np.array([[0,1,2],[3,4,5]])
b = x
print(b)

[[0 1 2]
 [3 4 5]]


In [126]:
# b is x, changing elements in x also change b
x[1,2]=-5
print('x=',x)
print('b=',b)

x= [[ 0  1  2]
 [ 3  4 -5]]
b= [[ 0  1  2]
 [ 3  4 -5]]


Why is that? Recall, `x = np.array([[0,1,2],[3,4,5]])` creates an object (in this case 2 by 3 array of integers) with data (values) 0,1,2,3,4,5, and makes the name `x` point to the object together its values.

`b = x` is equivalent to saying "b is x", it means that Python makes the name `b` also point to the same object as the name `x` has pointed to.

`x[1,2]=-5` changes (the values of) the object. Since `b` also points to the same object, `b[1,2]` is now also changed to -5.

If we make change to the object through `b`, it will also change `x` since both `b` and `x` point to the same object.

In [127]:
b[0,1] = 20
print('b=',b)
print('x=',x)

b= [[ 0 20  2]
 [ 3  4 -5]]
x= [[ 0 20  2]
 [ 3  4 -5]]


Case 2: The `copy` method makes a complete copy of an array and its data

In [128]:
x = np.array([[0,1,2],[3,4,5]])
b = x.copy()
print(b)

[[0 1 2]
 [3 4 5]]


Here, `b=x.copy()` means that Python created a new object (a 2 by 3 array of integers) that has the same data as the object that `x` represents.

`b` is independent of `x`, a change of the object through `b` does not affect the objected represented by `x`, vice versa.

`copy()` in Numpy is like the `deepcopy()` method in Python list.

In [129]:
b[0,1]=20
print('b=',b)
print('x=',x)

b= [[ 0 20  2]
 [ 3  4  5]]
x= [[0 1 2]
 [3 4 5]]


Sometimes `copy` should be called after slicing if the original array is not required anymore.

In [130]:
a = np.arange(int(1e8))        # a is a very large array
b = a[:20].copy()
del a
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Case 3: Different array objects can share the same data. Method `view` creates a new array object that _points to the same data_.

The method `view` in Numpy is like a shallow `copy` in Python.

In [131]:
x = np.array([[0,1,2],[3,4,5]])
a = x.view()
print('a=',a)
# changing the shape of a does not change the shape of x
a=a.reshape((3,2))
print('a=',a)
print('x=',x)
# but changing the value of a also changes the value of x
a[1,1]=-10
print('a=',a)
print('x=',x)

a= [[0 1 2]
 [3 4 5]]
a= [[0 1]
 [2 3]
 [4 5]]
x= [[0 1 2]
 [3 4 5]]
a= [[  0   1]
 [  2 -10]
 [  4   5]]
x= [[  0   1   2]
 [-10   4   5]]


## Computation on arrays

- Arithmetic operations
- Aggregation
- Arithmetic operations on more than one arrays
- Matrix and Vector operations

### Arithmetic operations

In [132]:
x = np.array([[0,1,2],[3,4,5]])
x+2

array([[2, 3, 4],
       [5, 6, 7]])

In [133]:
x % 2

array([[0, 1, 0],
       [1, 0, 1]])

In [134]:
-(0.1*x+3)**2

array([[ -9.  ,  -9.61, -10.24],
       [-10.89, -11.56, -12.25]])

In [135]:
np.round(np.sqrt(x), decimals=4)

array([[0.    , 1.    , 1.4142],
       [1.7321, 2.    , 2.2361]])

In [136]:
x = np.round(np.linspace(0.1,np.pi,4),decimals=4)
print('sin(x)=',np.sin(x))
print('e^x=',np.exp(x))
print('3^x=',np.power(3.,x))
print('log(x)=',np.log(x))

sin(x)= [ 9.98334166e-02  8.97426049e-01  8.48895773e-01 -7.34641021e-06]
e^x= [ 1.10517092  3.0462155   8.39553486 23.14086263]
3^x= [ 1.11612317  3.39989391 10.35549572 31.54453529]
log(x)= [-2.30258509  0.10786737  0.75504158  1.14473222]


### Aggregation

In [137]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [138]:
y = np.add.reduce(x)
y

np.int64(15)

In [139]:
y = np.multiply.reduce(x)
y

np.int64(120)

In [140]:
x = np.random.normal(size=(5,5))
print('x =',np.round(x,decimals=4))
print('mean(x)=',np.mean(x))
print('std(x)=',np.std(x))
print('var(x)=',np.var(x))
print('max(x)=',np.max(x))
print('argmax(x)=',np.argmax(x))   # counting, first row left to right, then second row left to right
print('sum(x)=',np.sum(x))
print('prod(x)=',np.prod(x))
print('cumprod(x)=',np.cumprod(x))
print('cumsum(x)=',np.cumsum(x))
print('any(x)=',np.any(x))

x = [[ 8.6080e-01  1.3009e+00  3.7146e+00  3.1903e+00  2.1810e-01]
 [-1.2550e-01  1.4239e+00  7.4810e-01 -7.9170e-01  1.0776e+00]
 [ 2.2391e+00 -1.4517e+00  3.1000e-03  3.0670e-01 -1.5618e+00]
 [-5.0890e-01 -6.8920e-01  1.0018e+00 -2.4755e+00 -2.5260e-01]
 [ 1.4600e-02 -1.6039e+00  1.3370e-01 -3.0040e-01 -8.1130e-01]]
mean(x)= 0.2264339307867863
std(x)= 1.421115563619171
var(x)= 2.019569445160634
max(x)= 3.7145779801419536
argmax(x)= 2
sum(x)= 5.660848269669658
prod(x)= -2.640786973291932e-07
cumprod(x)= [ 8.60785342e-01  1.11978062e+00  4.15951243e+00  1.32702810e+01
  2.89431540e+00 -3.63114339e-01 -5.17025506e-01 -3.86806128e-01
  3.06234762e-01  3.29993674e-01  7.38902195e-01 -1.07263827e+00
 -3.29473796e-03 -1.01050485e-03  1.57825476e-03 -8.03095978e-04
  5.53485986e-04  5.54491478e-04 -1.37263959e-03  3.46780157e-04
  5.05346251e-06 -8.10535224e-06 -1.08362883e-06  3.25508691e-07
 -2.64078697e-07]
cumsum(x)= [ 0.86078534  2.16166788  5.87624586  9.06659117  9.28469622  9.1592384

In [141]:
print('sum(x[:,])=',x.sum(axis=0))
print('prod(x[,:])=',x.prod(axis=1))

sum(x[:,])= [ 2.48018993 -1.02002888  5.60129667 -0.07053324 -1.3300762 ]
prod(x[,:])= [ 2.89431540e+00  1.14014414e-01  4.78268185e-03  2.19723815e-01
 -7.61516172e-04]


### Arithmetic operations on more than one arrays
These operations are element wise.

- `x+y` is equivalent to `np.add(x,y)`
- `x-y` is equivalent to `np.subtract(x,y)`
- `x*y` is equivalent to `np.multiply(x,y)`
- `x / y` is equivalent to `np.divide(x,y)`

In [142]:
x = np.random.normal(size=(2,3))
y = np.random.uniform(size=(2,3))
print('x =', np.round(x,decimals=4))
print('y =', np.round(y,decimals=4))

x = [[-1.2348 -0.3676  0.5404]
 [ 0.5856  0.5633 -1.6075]]
y = [[0.0651 0.7787 0.2793]
 [0.4508 0.8584 0.0581]]


In [143]:
# x*y is the element-wise product of two arrays, it is not the inner product.
x * y

array([[-0.08042956, -0.28621188,  0.15093515],
       [ 0.26396795,  0.48356913, -0.09346906]])

In [144]:
x+y

array([[-1.16969677,  0.41108843,  0.81970756],
       [ 1.03635355,  1.42174846, -1.5493509 ]])

In [145]:
x / y

array([[-18.9582928 ,  -0.47205575,   1.93489137],
       [  1.29890533,   0.65621725, -27.64599718]])

### Matrix and vector operations
We focus on two-dimensional arrays, which we call matrices. We call one-dimensional arrays vectors.

matrix multiplication requires the dimensions to align.

In [146]:
x = np.random.normal(size=(2,3))
y = np.random.uniform(size=(3,2))
print('x =', np.round(x,decimals=3))
print('y =', np.round(y,decimals=3))

x = [[ 0.82   0.044  2.968]
 [-0.903  1.289 -0.563]]
y = [[0.864 0.059]
 [0.785 0.37 ]
 [0.481 0.611]]


In [147]:
# matrix multiplication: use np.dot or @
np.dot(x,y)

array([[ 2.17120077,  1.87697597],
       [-0.03889813,  0.08080123]])

In [148]:
x @ y

array([[ 2.17120077,  1.87697597],
       [-0.03889813,  0.08080123]])

In [149]:
# We knew that x@y = y.T @ x.T
y.T @ x.T

array([[ 2.17120077, -0.03889813],
       [ 1.87697597,  0.08080123]])

In [150]:
# Of course x@y!= y@x
y @ x

array([[ 0.65547073,  0.11372206,  2.53187494],
       [ 0.3092869 ,  0.51200032,  2.12177421],
       [-0.15671062,  0.8082444 ,  1.08453096]])

In [151]:
# Inner product
np.inner(x[1,:],y[:,0])

np.float64(-0.03889813266504055)

In [152]:
np.inner(x,y.T)               # = x@y

array([[ 2.17120077,  1.87697597],
       [-0.03889813,  0.08080123]])

In [153]:
# Diagonal
x = np.reshape(np.linspace(0,15,16), (4,4))
print('x =',x)
y=np.diag(x)
y

x = [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


array([ 0.,  5., 10., 15.])

## File Input and Output

### Comma-separated values (CSV)
A common format for data files is comma-separated values (CSV), or related formats such as TSV (tab-separated values). To read data from such files into Numpy arrays we can use the `numpy.genfromtxt` function.

Example: Xvals2.csv contains four columns. It has thousands of rows, we read only 10 rows.

In [154]:
!head Xvals2.csv

"educm","heightm","BMIm","healthm"
2,186,28.905075,3
2,176,27.440599,3
3,187,23.163374,3
1,184,29.241493,2
1,174,23.781214,4
1,186,21.967857,3
2,183,25.082863,3
3,187,25.165146,3
2,183,23.589836,4


In [155]:
# male = np.genfromtxt('Xvals2.csv', delimiter=",", skip_header=1, names=["educm","heightm","BMIm","healthm"], max_rows=20)
male = np.genfromtxt('Xvals2.csv', delimiter=",", skip_header=1, max_rows=10)

In [156]:
male

array([[  2.      , 186.      ,  28.905075,   3.      ],
       [  2.      , 176.      ,  27.440599,   3.      ],
       [  3.      , 187.      ,  23.163374,   3.      ],
       [  1.      , 184.      ,  29.241493,   2.      ],
       [  1.      , 174.      ,  23.781214,   4.      ],
       [  1.      , 186.      ,  21.967857,   3.      ],
       [  2.      , 183.      ,  25.082863,   3.      ],
       [  3.      , 187.      ,  25.165146,   3.      ],
       [  2.      , 183.      ,  23.589836,   4.      ],
       [  2.      , 186.      ,  21.389755,   4.      ]])

In [157]:
male.shape

(10, 4)

Using `numpy.savetxt` we can store a Numpy array to a file in CSV format:

In [158]:
m = np.random.rand(3,3)
m

array([[0.02971394, 0.53684468, 0.12699461],
       [0.41129595, 0.31396715, 0.13403596],
       [0.19751608, 0.73531156, 0.73581855]])

In [159]:
np.savetxt("m.csv", m, fmt='%.5f')

In [160]:
!cat m.csv

0.02971 0.53684 0.12699
0.41130 0.31397 0.13404
0.19752 0.73531 0.73582


### Numpy's native file format

Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`:

In [161]:
np.save("m.npy", m)
!file m.npy

m.npy: NumPy data file, version 1.0, description {'descr': '<f8', 'fortran_order': False, 'shape': (3, 3), }                                                          


In [162]:
M=np.load("m.npy")
M

array([[0.02971394, 0.53684468, 0.12699461],
       [0.41129595, 0.31396715, 0.13403596],
       [0.19751608, 0.73531156, 0.73581855]])

## Further reading

[Numpy User Guide](https://numpy.org/doc/stable/user/index.html)